version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - {{buildCommand}}
  post_build:
    commands:
      - echo Build completed on `date`
      - {{packageCommand}}
  artifacts:
    files:
      - {{outputFile}}